project:
  type: website
  output-dir: docs

profile:
  default: spanish
  group: [english, spanish]

website:
  site-url: "https://martinolmos.github.io/data-icts/es"

format:
  html:
    include-after-body: disqus.html
